# Docker compose to run the docker image lluisb3/hl2ss (non-root image) #
# Build image running docker-build-script.sh to create user with same ID as host user #
# IMPORTANT to create directories in volumes on the host machine with user ownership before running #
# Set environment variables in .env file #

version: "3.8"

services:
  mask3d:
    image: lluisb3/hl2ss:${TAG}
    volumes:
      - ${OUTPUT_PATH}:/home/user/app/data
    container_name: pointcloud
    entrypoint: ["python3", "-u", "viewer/advanced_recorder.py", "--exp_name", "$EXP_NAME", "--ip_hololens", "$IP_HOLOLENS"]


